import { FoodNode, Edge } from "./types";

export const FOOD_NODES: Record<string, FoodNode> = {
  "idli": {
    id: "idli",
    name: "Idli",
    cuisine: ["South Indian"],
    ingredients: ["rice batter", "urad dal"],
    tags: ["steamed", "soft", "breakfast", "healthy", "mild"],
    type: "starter",
    isVegetarian: true,
  },
  "dosa": {
    id: "dosa",
    name: "Dosa",
    cuisine: ["South Indian"],
    ingredients: ["rice batter", "urad dal", "potato"],
    tags: ["crispy", "breakfast", "savory", "hot"],
    type: "starter",
    isVegetarian: true,
  },
  "biryani": {
    id: "biryani",
    name: "Biryani",
    cuisine: ["Mughlai", "South Indian", "North Indian"],
    ingredients: ["basmati rice", "spices", "chicken", "mutton", "saffron", "ghee"],
    tags: ["spicy", "heavy", "lunch", "dinner", "aromatic"],
    type: "combo",
    isVegetarian: false,
  },
  "paneer_butter_masala": {
    id: "paneer_butter_masala",
    name: "Paneer Butter Masala",
    cuisine: ["North Indian"],
    ingredients: ["paneer", "tomato", "butter", "cream", "spices"],
    tags: ["creamy", "rich", "sweet_and_spicy", "dinner"],
    type: "side",
    isVegetarian: true,
  },
  "chicken_tikka_masala": {
    id: "chicken_tikka_masala",
    name: "Chicken Tikka Masala",
    cuisine: ["North Indian"],
    ingredients: ["chicken", "tomato", "cream", "spices", "yogurt"],
    tags: ["creamy", "spicy", "roasted", "dinner"],
    type: "side",
    isVegetarian: false,
  },
  "butter_naan": {
    id: "butter_naan",
    name: "Butter Naan",
    cuisine: ["North Indian"],
    ingredients: ["maida", "butter", "yeast"],
    tags: ["bread", "soft", "heavy"],
    type: "addon",
    isVegetarian: true,
  },
  "raita": {
    id: "raita",
    name: "Raita",
    cuisine: ["North Indian", "South Indian"],
    ingredients: ["yogurt", "cucumber", "onion", "cumin"],
    tags: ["cold", "cooling", "side"],
    type: "addon",
    isVegetarian: true,
  },
  "sambar": {
    id: "sambar",
    name: "Sambar",
    cuisine: ["South Indian"],
    ingredients: ["toor dal", "tamarind", "vegetables", "spices"],
    tags: ["hot", "spicy", "tangy", "gravy"],
    type: "side",
    isVegetarian: true,
  },
  "filter_coffee": {
    id: "filter_coffee",
    name: "Filter Coffee",
    cuisine: ["South Indian", "Beverage"],
    ingredients: ["coffee decoction", "milk", "sugar"],
    tags: ["hot", "strong", "breakfast", "beverage"],
    type: "drink",
    isVegetarian: true,
  },
  "coke": {
    id: "coke",
    name: "Coca Cola",
    cuisine: ["Universal", "Beverage"],
    ingredients: ["carbonated water", "sugar", "caffeine"],
    tags: ["cold", "sweet", "fizzy", "beverage"],
    type: "drink",
    isVegetarian: true,
  },
  "gulab_jamun": {
    id: "gulab_jamun",
    name: "Gulab Jamun",
    cuisine: ["North Indian", "Dessert"],
    ingredients: ["khoya", "sugar", "rose water", "cardamom"],
    tags: ["sweet", "hot", "rich", "dessert"],
    type: "dessert",
    isVegetarian: true,
  },
  "falooda": {
    id: "falooda",
    name: "Falooda",
    cuisine: ["Mughlai", "Dessert", "Beverage"],
    ingredients: ["milk", "rose syrup", "vermicelli", "sweet basil seeds", "ice cream"],
    tags: ["cold", "sweet", "rich", "dessert"],
    type: "dessert",
    isVegetarian: true,
  },
  "french_fries": {
    id: "french_fries",
    name: "French Fries",
    cuisine: ["Fast Food"],
    ingredients: ["potato", "salt", "oil"],
    tags: ["crispy", "salty", "fried", "snack"],
    type: "side",
    isVegetarian: true,
  },
  "burger": {
    id: "burger",
    name: "Burger",
    cuisine: ["Fast Food"],
    ingredients: ["bun", "patty", "lettuce", "cheese"],
    tags: ["heavy", "snack"],
    type: "combo",
    isVegetarian: false, // assuming non-veg by default unless specified
  },
  "pizza": {
    id: "pizza",
    name: "Pizza",
    cuisine: ["Italian", "Fast Food"],
    ingredients: ["pizza dough", "cheese", "tomato sauce", "herbs"],
    tags: ["cheesy", "heavy", "baked", "dinner"],
    type: "combo",
    isVegetarian: true,
  }
};

// Pre-computed explicit relationships (mimicking a graph structure like KitcheNette)
export const EXPLICIT_EDGES: Edge[] = [
  { source: "biryani", target: "raita", weight: 0.95, reason: "Cools down the aromatic spices", type: "addon" },
  { source: "biryani", target: "coke", weight: 0.85, reason: "Perfect fizzy balance", type: "drink" },
  { source: "biryani", target: "falooda", weight: 0.8, reason: "Traditional rich sweet finish", type: "dessert" },
  { source: "idli", target: "sambar", weight: 0.98, reason: "Classic combination", type: "addon" },
  { source: "idli", target: "filter_coffee", weight: 0.9, reason: "Complete the South Indian breakfast", type: "drink" },
  { source: "dosa", target: "sambar", weight: 0.95, reason: "Essential dip", type: "addon" },
  { source: "paneer_butter_masala", target: "butter_naan", weight: 0.98, reason: "Perfect for scooping the creamy gravy", type: "combo" },
  { source: "chicken_tikka_masala", target: "butter_naan", weight: 0.98, reason: "Classic North Indian pairing", type: "combo" },
  { source: "paneer_butter_masala", target: "gulab_jamun", weight: 0.85, reason: "Sweet finish after a rich meal", type: "dessert" },
  { source: "burger", target: "french_fries", weight: 0.95, reason: "Best friends forever", type: "combo" },
  { source: "burger", target: "coke", weight: 0.9, reason: "Classic fast food combo", type: "drink" },
  { source: "pizza", target: "coke", weight: 0.9, reason: "Classic pairing", type: "drink" }
];
