import { FoodNode, Edge } from "./types";

export const FOOD_NODES: Record<string, FoodNode> = {
  "idli": {
    id: "idli",
    name: "Idli",
    cuisine: ["South Indian"],
    ingredients: ["rice batter", "urad dal"],
    tags: ["steamed", "soft", "breakfast", "healthy", "mild"],
    type: "starter",
    isVegetarian: true,
  },
  "dosa": {
    id: "dosa",
    name: "Dosa",
    cuisine: ["South Indian"],
    ingredients: ["rice batter", "urad dal", "potato"],
    tags: ["crispy", "breakfast", "savory", "hot"],
    type: "starter",
    isVegetarian: true,
  },
  "biryani": {
    id: "biryani",
    name: "Biryani",
    cuisine: ["Mughlai", "South Indian", "North Indian"],
    ingredients: ["basmati rice", "spices", "chicken", "mutton", "saffron", "ghee"],
    tags: ["spicy", "heavy", "lunch", "dinner", "aromatic"],
    type: "combo",
    isVegetarian: false,
  },
  "paneer_butter_masala": {
    id: "paneer_butter_masala",
    name: "Paneer Butter Masala",
    cuisine: ["North Indian"],
    ingredients: ["paneer", "tomato", "butter", "cream", "spices"],
    tags: ["creamy", "rich", "sweet_and_spicy", "dinner"],
    type: "side",
    isVegetarian: true,
  },
  "chicken_tikka_masala": {
    id: "chicken_tikka_masala",
    name: "Chicken Tikka Masala",
    cuisine: ["North Indian"],
    ingredients: ["chicken", "tomato", "cream", "spices", "yogurt"],
    tags: ["creamy", "spicy", "roasted", "dinner"],
    type: "side",
    isVegetarian: false,
  },
  "butter_naan": {
    id: "butter_naan",
    name: "Butter Naan",
    cuisine: ["North Indian"],
    ingredients: ["maida", "butter", "yeast"],
    tags: ["bread", "soft", "heavy"],
    type: "addon",
    isVegetarian: true,
  },
  "raita": {
    id: "raita",
    name: "Raita",
    cuisine: ["North Indian", "South Indian"],
    ingredients: ["yogurt", "cucumber", "onion", "cumin"],
    tags: ["cold", "cooling", "side"],
    type: "addon",
    isVegetarian: true,
  },
  "sambar": {
    id: "sambar",
    name: "Sambar",
    cuisine: ["South Indian"],
    ingredients: ["toor dal", "tamarind", "vegetables", "spices"],
    tags: ["hot", "spicy", "tangy", "gravy"],
    type: "side",
    isVegetarian: true,
  },
  "filter_coffee": {
    id: "filter_coffee",
    name: "Filter Coffee",
    cuisine: ["South Indian", "Beverage"],
    ingredients: ["coffee decoction", "milk", "sugar"],
    tags: ["hot", "strong", "breakfast", "beverage"],
    type: "drink",
    isVegetarian: true,
  },
  "coke": {
    id: "coke",
    name: "Coca Cola",
    cuisine: ["Universal", "Beverage"],
    ingredients: ["carbonated water", "sugar", "caffeine"],
    tags: ["cold", "sweet", "fizzy", "beverage"],
    type: "drink",
    isVegetarian: true,
  },
  "gulab_jamun": {
    id: "gulab_jamun",
    name: "Gulab Jamun",
    cuisine: ["North Indian", "Dessert"],
    ingredients: ["khoya", "sugar", "rose water", "cardamom"],
    tags: ["sweet", "hot", "rich", "dessert"],
    type: "dessert",
    isVegetarian: true,
  },
  "falooda": {
    id: "falooda",
    name: "Falooda",
    cuisine: ["Mughlai", "Dessert", "Beverage"],
    ingredients: ["milk", "rose syrup", "vermicelli", "sweet basil seeds", "ice cream"],
    tags: ["cold", "sweet", "rich", "dessert"],
    type: "dessert",
    isVegetarian: true,
  },
  "french_fries": {
    id: "french_fries",
    name: "French Fries",
    cuisine: ["Fast Food"],
    ingredients: ["potato", "salt", "oil"],
    tags: ["crispy", "salty", "fried", "snack"],
    type: "side",
    isVegetarian: true,
  },
  "burger": {
    id: "burger",
    name: "Burger",
    cuisine: ["Fast Food"],
    ingredients: ["bun", "patty", "lettuce", "cheese"],
    tags: ["heavy", "snack"],
    type: "combo",
    isVegetarian: false,
  },
  "pizza": {
    id: "pizza",
    name: "Pizza",
    cuisine: ["Italian", "Fast Food"],
    ingredients: ["pizza dough", "cheese", "tomato sauce", "herbs"],
    tags: ["cheesy", "heavy", "baked", "dinner"],
    type: "combo",
    isVegetarian: true,
  },
  "pasta": {
    id: "pasta",
    name: "Pasta",
    cuisine: ["Italian"],
    ingredients: ["pasta", "sauce", "cheese"],
    tags: ["heavy", "dinner", "creamy"],
    type: "combo",
    isVegetarian: true,
  },
  
  // --- CHUTNEYS ---
  "coconut_chutney": {
    id: "coconut_chutney",
    name: "Coconut Chutney",
    cuisine: ["South Indian"],
    ingredients: ["coconut", "green chili", "ginger", "curry leaves"],
    tags: ["dip", "cold", "healthy", "side", "essential"],
    type: "side",
    isVegetarian: true,
  },
  "tomato_chutney": {
    id: "tomato_chutney",
    name: "Tomato Chutney",
    cuisine: ["South Indian"],
    ingredients: ["tomato", "onion", "red chili"],
    tags: ["dip", "tangy", "spicy", "side"],
    type: "side",
    isVegetarian: true,
  },
  "kara_chutney": {
    id: "kara_chutney",
    name: "Kara Chutney",
    cuisine: ["South Indian"],
    ingredients: ["red chili", "garlic", "tomato"],
    tags: ["dip", "spicy", "garlic", "side"],
    type: "side",
    isVegetarian: true,
  },
  "onion_chutney": {
    id: "onion_chutney",
    name: "Onion Chutney",
    cuisine: ["South Indian"],
    ingredients: ["onion", "red chili", "tamarind"],
    tags: ["dip", "savory", "tangy", "side"],
    type: "side",
    isVegetarian: true,
  },
  "peanut_chutney": {
    id: "peanut_chutney",
    name: "Peanut Chutney",
    cuisine: ["South Indian"],
    ingredients: ["peanuts", "green chili", "tamarind"],
    tags: ["dip", "nutty", "creamy", "side"],
    type: "side",
    isVegetarian: true,
  },
  "mint_chutney": {
    id: "mint_chutney",
    name: "Mint Chutney",
    cuisine: ["South Indian"],
    ingredients: ["mint", "coriander", "green chili"],
    tags: ["dip", "fresh", "spicy", "side"],
    type: "side",
    isVegetarian: true,
  },
  "garlic_chutney": {
    id: "garlic_chutney",
    name: "Garlic Chutney",
    cuisine: ["South Indian"],
    ingredients: ["garlic", "red chili", "oil"],
    tags: ["dip", "spicy", "pungent", "side"],
    type: "side",
    isVegetarian: true,
  },
  "curry_leaf_chutney": {
    id: "curry_leaf_chutney",
    name: "Curry Leaf Chutney",
    cuisine: ["South Indian"],
    ingredients: ["curry leaves", "urad dal", "spices"],
    tags: ["dip", "healthy", "herbal", "side"],
    type: "side",
    isVegetarian: true,
  },
  "coriander_chutney": {
    id: "coriander_chutney",
    name: "Coriander Chutney",
    cuisine: ["South Indian"],
    ingredients: ["coriander", "green chili", "coconut"],
    tags: ["dip", "fresh", "herbal", "side"],
    type: "side",
    isVegetarian: true,
  },
  "beetroot_chutney": {
    id: "beetroot_chutney",
    name: "Beetroot Chutney",
    cuisine: ["South Indian"],
    ingredients: ["beetroot", "coconut", "mustard seeds"],
    tags: ["dip", "sweet_and_spicy", "vibrant", "side"],
    type: "side",
    isVegetarian: true,
  },

  // --- SAMSAR & SIDES ---
  "tiffin_sambar": {
    id: "tiffin_sambar",
    name: "Tiffin Sambar",
    cuisine: ["South Indian"],
    ingredients: ["lentils", "sambar powder", "shallots", "tamarind"],
    tags: ["hot", "tangy", "essential", "side"],
    type: "side",
    isVegetarian: true,
  },
  "onion_sambar": {
    id: "onion_sambar",
    name: "Onion Sambar",
    cuisine: ["South Indian"],
    ingredients: ["small onions", "lentils", "tamarind"],
    tags: ["hot", "sweet_and_tangy", "side"],
    type: "side",
    isVegetarian: true,
  },
  "potato_masala": {
    id: "potato_masala",
    name: "Potato Masala",
    cuisine: ["South Indian"],
    ingredients: ["potato", "onion", "turmeric", "green chili"],
    tags: ["savory", "filling", "side"],
    type: "side",
    isVegetarian: true,
  },
  "vegetable_kurma": {
    id: "vegetable_kurma",
    name: "Vegetable Kurma",
    cuisine: ["South Indian"],
    ingredients: ["mixed vegetables", "coconut", "poppy seeds", "spices"],
    tags: ["creamy", "mild", "rich", "side"],
    type: "side",
    isVegetarian: true,
  },
  "rasam_cup": {
    id: "rasam_cup",
    name: "Rasam Cup",
    cuisine: ["South Indian"],
    ingredients: ["tamarind", "tomato", "pepper", "cumin"],
    tags: ["hot", "spicy", "digestive", "side"],
    type: "side",
    isVegetarian: true,
  },

  // --- ADDONS ---
  "ghee_podi": {
    id: "ghee_podi",
    name: "Ghee Podi",
    cuisine: ["South Indian"],
    ingredients: ["idli podi", "ghee"],
    tags: ["spicy", "rich", "dry_dip", "addon"],
    type: "addon",
    isVegetarian: true,
  },
  "milagai_podi": {
    id: "milagai_podi",
    name: "Milagai Podi",
    cuisine: ["South Indian"],
    ingredients: ["lentils", "red chili", "sesame seeds"],
    tags: ["spicy", "dry_dip", "addon"],
    type: "addon",
    isVegetarian: true,
  },
  "extra_ghee": {
    id: "extra_ghee",
    name: "Extra Ghee",
    cuisine: ["Universal"],
    ingredients: ["clarified butter"],
    tags: ["rich", "topping", "addon"],
    type: "addon",
    isVegetarian: true,
  },
  "gun_powder": {
    id: "gun_powder",
    name: "Gun Powder",
    cuisine: ["South Indian"],
    ingredients: ["lentils", "red chili", "garlic"],
    tags: ["extra_spicy", "dry_dip", "addon"],
    type: "addon",
    isVegetarian: true,
  },

  // --- MINI SIDES ---
  "mini_idli": {
    id: "mini_idli",
    name: "Mini Idli",
    cuisine: ["South Indian"],
    ingredients: ["rice batter"],
    tags: ["steamed", "soft", "bite_sized", "breakfast"],
    type: "starter",
    isVegetarian: true,
  },
  "kuzhi_paniyaram": {
    id: "kuzhi_paniyaram",
    name: "Kuzhi Paniyaram",
    cuisine: ["South Indian"],
    ingredients: ["fermented batter", "onions", "chillies"],
    tags: ["crispy", "soft_inside", "starter"],
    type: "starter",
    isVegetarian: true,
  },
  "sweet_paniyaram": {
    id: "sweet_paniyaram",
    name: "Sweet Paniyaram",
    cuisine: ["South Indian"],
    ingredients: ["fermented batter", "jaggery", "cardamom"],
    tags: ["sweet", "soft", "starter", "dessert"],
    type: "dessert",
    isVegetarian: true,
  }
};

// Pre-computed explicit relationships (mimicking a graph structure like KitcheNette)
export const EXPLICIT_EDGES: Edge[] = [
  { source: "biryani", target: "chicken_65", weight: 0.98, reason: "Spicy starter combo", type: "starter" },
  { source: "biryani", target: "raita", weight: 0.95, reason: "Cools down the aromatic spices", type: "addon" },
  { source: "biryani", target: "coke", weight: 0.85, reason: "Perfect fizzy balance", type: "drink" },
  { source: "biryani", target: "gulab_jamun", weight: 0.9, reason: "Sweet finish after a rich meal", type: "dessert" },
  { source: "biryani", target: "falooda", weight: 0.8, reason: "Traditional rich sweet finish", type: "dessert" },
  
  { source: "idli", target: "tiffin_sambar", weight: 0.99, reason: "Classic combination", type: "side" },
  { source: "idli", target: "coconut_chutney", weight: 0.98, reason: "Essential South Indian dip", type: "side" },
  { source: "idli", target: "vada", weight: 0.9, reason: "Make it a complete breakfast", type: "combo" },
  { source: "idli", target: "filter_coffee", weight: 0.9, reason: "Complete the South Indian breakfast", type: "drink" },
  { source: "idli", target: "milagai_podi", weight: 0.95, reason: "Spicy crunch pairing", type: "addon" },
  { source: "idli", target: "extra_ghee", weight: 0.9, reason: "Rich traditional taste", type: "addon" },
  
  { source: "masala_dosa", target: "tiffin_sambar", weight: 0.98, reason: "Classic pairing", type: "side" },
  { source: "masala_dosa", target: "coconut_chutney", weight: 0.99, reason: "Essential dip", type: "side" },
  { source: "masala_dosa", target: "potato_masala", weight: 0.99, reason: "The soul of masala dosa", type: "side" },
  { source: "masala_dosa", target: "medu_vada", weight: 0.9, reason: "Classic breakfast combo", type: "combo" },
  
  { source: "dosa", target: "coconut_chutney", weight: 0.99, reason: "Essential dip", type: "side" },
  { source: "dosa", target: "tomato_chutney", weight: 0.95, reason: "Tangy & spicy twist", type: "side" },
  { source: "dosa", target: "tiffin_sambar", weight: 0.98, reason: "The perfect dip", type: "side" },
  { source: "dosa", target: "filter_coffee", weight: 0.9, reason: "Authentic breakfast finish", type: "drink" },

  { source: "rava_dosa", target: "coconut_chutney", weight: 0.99, reason: "Essential dip", type: "side" },
  { source: "rava_dosa", target: "tomato_chutney", weight: 0.95, reason: "Pairs perfectly with rava texture", type: "side" },
  
  { source: "pongal", target: "medu_vada", weight: 0.95, reason: "Traditional breakfast pairing", type: "combo" },
  { source: "pongal", target: "coconut_chutney", weight: 0.98, reason: "Smooth dip for soft pongal", type: "side" },
  
  { source: "paratha", target: "lassi", weight: 0.95, reason: "Authentic North Indian experience", type: "drink" },
  { source: "paratha", target: "raita", weight: 0.85, reason: "Cooling side for spicy paratha", type: "side" },
  
  { source: "poori_bhaji", target: "masala_tea", weight: 0.85, reason: "Classic tea-time combo", type: "drink" },
  
  { source: "paneer_butter_masala", target: "butter_naan", weight: 0.98, reason: "Perfect for scooping the creamy gravy", type: "combo" },
  { source: "chicken_tikka_masala", target: "butter_naan", weight: 0.98, reason: "Classic North Indian pairing", type: "combo" },
  
  { source: "burger", target: "french_fries", weight: 0.95, reason: "Best friends forever", type: "combo" },
  { source: "burger", target: "coke", weight: 0.9, reason: "Classic fast food combo", type: "drink" },
  
  { source: "pizza", target: "garlic_bread", weight: 0.98, reason: "Perfect baked side", type: "side" },
  { source: "pizza", target: "coke", weight: 0.9, reason: "Classic pairing", type: "drink" }
];
