import { FoodNode, Edge } from "./types";

export const FOOD_NODES: Record<string, FoodNode> = {
  "idli": {
    id: "idli",
    name: "Idli",
    cuisine: ["South Indian"],
    ingredients: ["rice batter", "urad dal"],
    tags: ["steamed", "soft", "breakfast", "healthy", "mild"],
    type: "starter",
    isVegetarian: true,
  },
  "dosa": {
    id: "dosa",
    name: "Dosa",
    cuisine: ["South Indian"],
    ingredients: ["rice batter", "urad dal", "potato"],
    tags: ["crispy", "breakfast", "savory", "hot"],
    type: "starter",
    isVegetarian: true,
  },
  "biryani": {
    id: "biryani",
    name: "Biryani",
    cuisine: ["Mughlai", "South Indian", "North Indian"],
    ingredients: ["basmati rice", "spices", "chicken", "mutton", "saffron", "ghee"],
    tags: ["spicy", "heavy", "lunch", "dinner", "aromatic"],
    type: "combo",
    isVegetarian: false,
  },
  "paneer_butter_masala": {
    id: "paneer_butter_masala",
    name: "Paneer Butter Masala",
    cuisine: ["North Indian"],
    ingredients: ["paneer", "tomato", "butter", "cream", "spices"],
    tags: ["creamy", "rich", "sweet_and_spicy", "dinner"],
    type: "side",
    isVegetarian: true,
  },
  "chicken_tikka_masala": {
    id: "chicken_tikka_masala",
    name: "Chicken Tikka Masala",
    cuisine: ["North Indian"],
    ingredients: ["chicken", "tomato", "cream", "spices", "yogurt"],
    tags: ["creamy", "spicy", "roasted", "dinner"],
    type: "side",
    isVegetarian: false,
  },
  "butter_naan": {
    id: "butter_naan",
    name: "Butter Naan",
    cuisine: ["North Indian"],
    ingredients: ["maida", "butter", "yeast"],
    tags: ["bread", "soft", "heavy"],
    type: "addon",
    isVegetarian: true,
  },
  "raita": {
    id: "raita",
    name: "Raita",
    cuisine: ["North Indian", "South Indian"],
    ingredients: ["yogurt", "cucumber", "onion", "cumin"],
    tags: ["cold", "cooling", "side"],
    type: "addon",
    isVegetarian: true,
  },
  "sambar": {
    id: "sambar",
    name: "Sambar",
    cuisine: ["South Indian"],
    ingredients: ["toor dal", "tamarind", "vegetables", "spices"],
    tags: ["hot", "spicy", "tangy", "gravy"],
    type: "side",
    isVegetarian: true,
  },
  "filter_coffee": {
    id: "filter_coffee",
    name: "Filter Coffee",
    cuisine: ["South Indian", "Beverage"],
    ingredients: ["coffee decoction", "milk", "sugar"],
    tags: ["hot", "strong", "breakfast", "beverage"],
    type: "drink",
    isVegetarian: true,
  },
  "coke": {
    id: "coke",
    name: "Coca Cola",
    cuisine: ["Universal", "Beverage"],
    ingredients: ["carbonated water", "sugar", "caffeine"],
    tags: ["cold", "sweet", "fizzy", "beverage"],
    type: "drink",
    isVegetarian: true,
  },
  "gulab_jamun": {
    id: "gulab_jamun",
    name: "Gulab Jamun",
    cuisine: ["North Indian", "Dessert"],
    ingredients: ["khoya", "sugar", "rose water", "cardamom"],
    tags: ["sweet", "hot", "rich", "dessert"],
    type: "dessert",
    isVegetarian: true,
  },
  "falooda": {
    id: "falooda",
    name: "Falooda",
    cuisine: ["Mughlai", "Dessert", "Beverage"],
    ingredients: ["milk", "rose syrup", "vermicelli", "sweet basil seeds", "ice cream"],
    tags: ["cold", "sweet", "rich", "dessert"],
    type: "dessert",
    isVegetarian: true,
  },
  "french_fries": {
    id: "french_fries",
    name: "French Fries",
    cuisine: ["Fast Food"],
    ingredients: ["potato", "salt", "oil"],
    tags: ["crispy", "salty", "fried", "snack"],
    type: "side",
    isVegetarian: true,
  },
  "burger": {
    id: "burger",
    name: "Burger",
    cuisine: ["Fast Food"],
    ingredients: ["bun", "patty", "lettuce", "cheese"],
    tags: ["heavy", "snack"],
    type: "combo",
    isVegetarian: false, // assuming non-veg by default unless specified
  },
  "pizza": {
    id: "pizza",
    name: "Pizza",
    cuisine: ["Italian", "Fast Food"],
    ingredients: ["pizza dough", "cheese", "tomato sauce", "herbs"],
    tags: ["cheesy", "heavy", "baked", "dinner"],
    type: "combo",
    isVegetarian: true,
  },
  "coconut_chutney": {
    id: "coconut_chutney",
    name: "Coconut Chutney",
    cuisine: ["South Indian"],
    ingredients: ["coconut", "green chili", "ginger"],
    tags: ["dip", "cold", "healthy", "side"],
    type: "addon",
    isVegetarian: true,
  },
  "vada": {
    id: "vada",
    name: "Vada",
    cuisine: ["South Indian"],
    ingredients: ["urad dal", "spices"],
    tags: ["crispy", "savory", "hot", "breakfast"],
    type: "side",
    isVegetarian: true,
  },
  "masala_tea": {
    id: "masala_tea",
    name: "Masala Tea",
    cuisine: ["Indian", "Beverage"],
    ingredients: ["tea leaves", "milk", "ginger", "cardamom"],
    tags: ["hot", "aromatic", "beverage"],
    type: "drink",
    isVegetarian: true,
  },
  "masala_dosa": {
    id: "masala_dosa",
    name: "Masala Dosa",
    cuisine: ["South Indian"],
    ingredients: ["rice batter", "potato", "onion", "spices"],
    tags: ["crispy", "savory", "popular", "breakfast", "filling"],
    type: "combo",
    isVegetarian: true,
  },
  "rava_dosa": {
    id: "rava_dosa",
    name: "Rava Dosa",
    cuisine: ["South Indian"],
    ingredients: ["semolina", "rice flour", "peppercorns", "ginger"],
    tags: ["extra_crispy", "quick", "breakfast"],
    type: "combo",
    isVegetarian: true,
  },
  "pongal": {
    id: "pongal",
    name: "Pongal",
    cuisine: ["South Indian"],
    ingredients: ["rice", "moong dal", "pepper", "cumin", "ghee"],
    tags: ["soft", "comfort_food", "breakfast", "healthy"],
    type: "combo",
    isVegetarian: true,
  },
  "poori_bhaji": {
    id: "poori_bhaji",
    name: "Poori Bhaji",
    cuisine: ["Indian"],
    ingredients: ["wheat flour", "potato", "spices"],
    tags: ["fried", "savory", "breakfast", "filling"],
    type: "combo",
    isVegetarian: true,
  },
  "paratha": {
    id: "paratha",
    name: "Paratha",
    cuisine: ["North Indian"],
    ingredients: ["whole wheat", "ghee", "potato/paneer"],
    tags: ["bread", "heavy", "breakfast", "lunch"],
    type: "combo",
    isVegetarian: true,
  },
  "lassi": {
    id: "lassi",
    name: "Lassi",
    cuisine: ["North Indian", "Beverage"],
    ingredients: ["curd", "sugar", "cardamom"],
    tags: ["cold", "sweet", "thick", "beverage"],
    type: "drink",
    isVegetarian: true,
  },
  "buttermilk": {
    id: "buttermilk",
    name: "Buttermilk",
    cuisine: ["Indian", "Beverage"],
    ingredients: ["curd", "water", "salt", "ginger", "curry leaves"],
    tags: ["cold", "salted", "cooling", "digestive"],
    type: "drink",
    isVegetarian: true,
  },
  "medu_vada": {
    id: "medu_vada",
    name: "Medu Vada",
    cuisine: ["South Indian"],
    ingredients: ["urad dal", "spices"],
    tags: ["crispy", "savory", "breakfast"],
    type: "side",
    isVegetarian: true,
  }
};

// Pre-computed explicit relationships (mimicking a graph structure like KitcheNette)
export const EXPLICIT_EDGES: Edge[] = [
  { source: "biryani", target: "raita", weight: 0.95, reason: "Cools down the aromatic spices", type: "addon" },
  { source: "biryani", target: "coke", weight: 0.85, reason: "Perfect fizzy balance", type: "drink" },
  { source: "biryani", target: "falooda", weight: 0.8, reason: "Traditional rich sweet finish", type: "dessert" },
  { source: "idli", target: "sambar", weight: 0.98, reason: "Classic combination", type: "addon" },
  { source: "idli", target: "coconut_chutney", weight: 0.98, reason: "Essential South Indian dip", type: "addon" },
  { source: "idli", target: "vada", weight: 0.9, reason: "Make it a complete breakfast", type: "combo" },
  { source: "idli", target: "filter_coffee", weight: 0.9, reason: "Complete the South Indian breakfast", type: "drink" },
  { source: "masala_dosa", target: "sambar", weight: 0.98, reason: "Classic pairing", type: "addon" },
  { source: "masala_dosa", target: "coconut_chutney", weight: 0.98, reason: "Essential dip", type: "addon" },
  { source: "masala_dosa", target: "medu_vada", weight: 0.9, reason: "Classic breakfast combo", type: "combo" },
  { source: "rava_dosa", target: "coconut_chutney", weight: 0.98, reason: "Essential dip", type: "addon" },
  { source: "pongal", target: "medu_vada", weight: 0.95, reason: "Traditional breakfast pairing", type: "combo" },
  { source: "paratha", target: "lassi", weight: 0.95, reason: "Authentic North Indian experience", type: "drink" },
  { source: "paratha", target: "raita", weight: 0.85, reason: "Cooling side for spicy paratha", type: "addon" },
  { source: "poori_bhaji", target: "masala_tea", weight: 0.85, reason: "Classic tea-time combo", type: "drink" },
  { source: "dosa", target: "sambar", weight: 0.95, reason: "Essential dip", type: "addon" },
  { source: "dosa", target: "coconut_chutney", weight: 0.98, reason: "Perfectly complements the crispy dosa", type: "addon" },
  { source: "dosa", target: "vada", weight: 0.85, reason: "Crispy duo", type: "combo" },
  { source: "dosa", target: "masala_tea", weight: 0.8, reason: "Warm finish to your meal", type: "drink" },
  { source: "paneer_butter_masala", target: "butter_naan", weight: 0.98, reason: "Perfect for scooping the creamy gravy", type: "combo" },
  { source: "chicken_tikka_masala", target: "butter_naan", weight: 0.98, reason: "Classic North Indian pairing", type: "combo" },
  { source: "paneer_butter_masala", target: "gulab_jamun", weight: 0.85, reason: "Sweet finish after a rich meal", type: "dessert" },
  { source: "burger", target: "french_fries", weight: 0.95, reason: "Best friends forever", type: "combo" },
  { source: "burger", target: "coke", weight: 0.9, reason: "Classic fast food combo", type: "drink" },
  { source: "pizza", target: "coke", weight: 0.9, reason: "Classic pairing", type: "drink" }
];
